package main

var dockerfileMokr = `# generated by mokr - changes will be overwritten
FROM {{ .Runner }}
MAINTAINER {{ .Author }}
ADD {{ .Slugfile }}slug.tgz /app
ENV GIT_SHA1 {{ .Sha1 }}
ENV GIT_BRANCH {{ .Branch }}
{{ .Include }}
ENTRYPOINT ["/runner/init"]`
